# Generated by Django 4.2.18 on 2025-02-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.estado')),
            ],
        ),
    ]
