# Generated by Django 4.2.18 on 2025-02-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_rename_estado_cidade_estado_endereço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereço',
            name='cep',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='endereço',
            name='numero',
            field=models.IntegerField(max_length=5),
        ),
    ]
