# Generated by Django 4.2.18 on 2025-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_endereço_cep_alter_endereço_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereço',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='endereço',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
